### PR TITLE
Code block added where needed

### PR DESCRIPTION
**Pull request by rmariuzzo**
Hey @iominh!

I added a few code block markup to your existing `README` file.

### CODE REVIEW

**Comment by iominh** [comment]
Thanks @rmariuzzo!! It's very appreciated

**Comment by rmariuzzo** [comment]
You are welcome! By the way, I'm using this awesome lib into a personal project! Thank you!

**Comment by iominh** [comment]
That's awesome! Is that project public by chance? I could perhaps link it from this project or maybe add it to the wiki

If not no worries I'm just glad this project helped :)

**Comment by rmariuzzo** [comment]
@iominh it will be public soon, currently it is still private. ;)

**Pull request merged**
